@WhatAndWhen_HostAddress = http://localhost:5016




POST {{WhatAndWhen_HostAddress}}/api/commentapi
Content-Type: application/json

{
  "content": "TestComment5",
  "taskId": 1
  
}

###

@id=2
GET {{WhatAndWhen_HostAddress}}/api/commentapi/{{id}}

###

DELETE {{WhatAndWhen_HostAddress}}/api/commentapi/{{id}}

###

PUT {{WhatAndWhen_HostAddress}}/api/commentapi/{{id}}
Content-Type: application/json

{
  "content": "TestComment2",
  "taskId": 1
}

###

GET {{WhatAndWhen_HostAddress}}/api/commentapi

###

GET {{WhatAndWhen_HostAddress}}/api/commentapi

###
